name: Ubuntu Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v4
    - name: install boost-1.83
      shell: bash
      run: |
         sudo add-apt-repository ppa:mhier/libboost-latest
         sudo apt update
         sudo apt-get install -y libboost1.83-all-dev
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
